spring:
  application:
    name: spring_ai
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


upload:
  path: src/main/resources/static/uploads/