-- apt-get update \
-- && apt-get install -y postgresql-server-dev-all build-essential git \
-- && git clone --branch v0.7.0 https://github.com/pgvector/pgvector.git /pgvector \
-- && cd /pgvector && make && make install